### PR TITLE
Enhancement | Search Results UI

### LINKED ISSUE #170: Enhancement | Search Results UI
### Current
The Search results UI is pretty basic at the moment.

### Expectation:
Take inspiration from this design and build something similar:
https://dribbble.com/shots/24103501-Search-Results-Animation

### Things to consider:
- The search result can have Blogs, Users, Topics
- The search feature is currently hidden for mobile screens, but consider making this design responsive for all screens.
- Observe the intricacies of the design of the dribbble link. The transitions, the borders, the colours, the shortcuts.

Screenshot 2024-06-13 at 10 49 30 AM

Screenshot 2024-06-13 at 10 49 23 AM

### PR DESCRIPTION
**Pull request by Nexonikk**
# Enhanced search results UI

resolves #170 

## Description

1- Implemented Search spinner/loader in input.
2- Added a new feature of highlighted text, it will highlight the text of the input in search results.
3- Added search scroll, because if the results are lengthy it is blocking whole UI.

"I tried to make the search results UI as similar as it could be to the Dribble video."

**Consider watching attachment below to have the exact idea about the task**

https://github.com/user-attachments/assets/f70a506b-811d-44b1-aa05-ff3a4c4d1c23

### CODE REVIEW

**Comment by Nexonikk** [comment]
@aadeshkulkarni checkout this PR

**Comment by aadeshkulkarni** [comment]
features look good. but UI can be better.

**Comment by Nexonikk** [comment]
> features look good. but UI can be better.

I made the ui according to the theme of the website i tried my best make the ui look good.  what else can be changed any suggestions?

**Comment by aadeshkulkarni** [comment]
> > features look good. but UI can be better.
> 
> I made the ui according to the theme of the website i tried my best make the ui look good. what else can be changed any suggestions?

Refer this https://dribbble.com/shots/24103501-Search-Results-Animation

**Comment by aadeshkulkarni** [comment]
frontend undergoing redesign. this is paused for the moment. apologies.

**Pull request closed without merging**
