### PR TITLE
Feature | Google OAuth

### LINKED ISSUE #8: Feature | Google Signup
Users should be able to use the app using Google SSO effortlessly.

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
# Google Oauth service integration

Resolves #8 

- New feature (non-breaking change which adds functionality)
- Documentation update

## Changes

- [x] frontend
- [x] backend

## Recording

https://github.com/user-attachments/assets/ff113feb-40ed-4ac6-8f1c-63c3117533c5

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I assure there are no similar/duplicate pull requests regarding the same issue
- [x] My changes follow the project's coding guidelines and best practices
- [x] Code is formatted properly and lint check passes successfully
- [ ] I have made corresponding changes to the documentation (if applicable)

### CODE REVIEW

**Comment by Ashutoshpadhi629** [comment]
@aadeshkulkarni can you review This ?

**Review by aadeshkulkarni — APPROVED** [review]

**Comment by aadeshkulkarni** [comment]
Thank you for your contribution!

**Comment by aadeshkulkarni** [comment]
Please fix the following build time errors
Screenshot 2024-07-21 at 8 54 25 PM

**Comment by Ashutoshpadhi629** [comment]
@aadeshkulkarni done

**Pull request merged**
