### PR TITLE
Fix issue 256: Bugfix | Tags with 0 posts

### LINKED ISSUE #241: Bug | Topics with 0 posts
### Current:
All topics are displayed at the top. Even topics with 0 posts.

### Expectation:
- Show only those topics which have at least 1 post.
- Sort topics by count(posts)

### Note:
- Implement this in the backend

### PR DESCRIPTION
**Pull request by vverma022**
# Topic Slider Changes 

## Description

Fixes the Bug where the Topic's with 0 posts are not shown in the topic slider and the slider is sorted in descending order.

Resolves #256 

- Fixes #241 
- Closes #241 

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

## Changes

- Added a sorting on the TagRouter.get which where the tags now will be fetched and sent in descending order on the basis of posts associated with them.
- In the font-end while fetching the tags using fetch-topic hook a filter has been added which filters the posts and shows only the ones with more than 0 posts.
- To achieve the above the backend now sends 3 objects id, name  and count which is the count of the number of posts in each topic. this enables us to filter them and can also be used for implementing other features like topic post count etc. The interface was also modified to accept a count.

## Checklist before requesting a review

-  have performed a self-review of my code
-  I assure there are no similar/duplicate pull requests regarding the same issue
-  My changes follow the project's coding guidelines and best practices
-  Code is formatted properly and lint check passes successfully
-  have made corresponding changes to the documentation (if applicable)

## Additional Notes

The reason for such is hybrid approach is because when the backend route was implementing the filter to send only topics with > 0 posts other components which are using that route were affected for example the component which lets you select which topic a post should be associated with etc.

### CODE REVIEW

**Comment by aadeshkulkarni** [comment]
@vverma022 - The tags slider isn't shown even though the API returns data. 

Screenshot 2024-09-04 at 12 22 50 PM

**Comment by vverma022** [comment]
Screenshot 2024-09-10 at 12 32 03 AM
It's working here.

**Comment by vverma022** [comment]
> @vverma022 - The tags slider isn't shown even though the API returns data.
> 
> Screenshot 2024-09-04 at 12 22 50 PM

I can't seem to find the problem as it's working fine for me. I'm able to filter the tags and show only the ones with posts > 0 and in desending order.

**Comment by aadeshkulkarni** [comment]
frontend undergoing redesign. this is paused for the moment. apologies.

**Pull request closed without merging**
