### PR TITLE
Fixed R2 files for Local Development

### LINKED ISSUE #125: 25$ Bounty | Local Development: Cloudflare Worker (HonoJS) Accessing R2 Files
### Scenario:

Our backend is a cloudflare worker. It's a serverless architecture. Cloudflare also provides R2, an object store, like AWS S3, to manage file uploads. 

When we upload a file from production instance, the file gets uploaded to the R2 bucket successfully, and a key is generated.
To access this uploaded file, we can setup subdomains that facilitate a base-url that can be used for the file downloads. 

**file-path = subDomainUrl + key** 

> wrangler.toml file > R2_SUBDOMAIN_URL 

<hr />

### Here is the catch:

When we upload a file from dev mode (locally), the file gets uploaded to the local cache (within .wrangler/state/../R2/blob) instead of the R2 bucket.
Now, To access this uploaded file, we need a url.
Without the url, we cannot generate a file path.  
And without the filepath, we cannot access the file on the frontend.

<hr />

I'd like to find a solution that allows me (developer) to test my Worker's upload & download file functionality with Cloudflare R2 **during local development**. 

For example, from local dev instance, A user should be able to successfully upload their profile picture and should be able to access the profile picture as a url.

- Use CloudFlare R2 only

### Points to consider:
- frontend/src/config.ts > FF_IMAGE_UPLOADS = false - will disable the upload feature.
- wrangler.toml > The configuration file for Cloudfare wrangler
- backend/.wrangler > will contain uploaded file blobs when app is running using `npm run dev`

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
# Fixed R2 files for Local Development

## Description

Now we can access R2 files in local development.
Also fixed the app bar profile avatar.

## Changes

- Removed `wrangler.toml` and added `wrangler.sample.toml`
- Added a `preview_bucket_name` for dev mode
- Fixed the app bar profile avatar

- Fixes #125 

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

## Recording

https://github.com/aadeshkulkarni/figuringout/assets/81710269/f579ad5a-c572-492c-af91-a60ee8077b17

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I assure there are no similar/duplicate pull requests regarding the same issue
- [x] My changes follow the project's coding guidelines and best practices
- [x] Code is formatted properly and lint check passes successfully
- [x] I have made corresponding changes to the documentation (if applicable)

## Additional Notes

Developers should have access to a bucket on their own Cloudflare account.
[Reference Video](https://www.youtube.com/watch?v=VEATzKttaMI)

### CODE REVIEW

**Comment by aadeshkulkarni** [comment]
I think, the local setup looks fishy. The frontend is probably pointing to the remote backend instance, instead of pointing to your local backend instance. (Check frontend/src/config.ts - BACKEND_URL)

Please share a video with the following:
- Start with showing your frontend/src/config.ts - The BACKEND_URL should be pointing to localhost:8787
- Spin up both frontend and backend servers
- Run the app, upload the profile picture.
- Connect to your Postgres Database (using Pg Admin / psql) ->  fetch the profilePic url from the User table and show the path where the images are getting saved.

**Comment by Ashutoshpadhi629** [comment]
Video part 1 
* `config.ts` points to local backend
* shows both the frontend and backend
* updated the profile pic

https://github.com/aadeshkulkarni/figuringout/assets/81710269/58d86011-f7de-4ba9-a94f-7c748427695e

Video part 2
* used prisma studio to show the users table

https://github.com/aadeshkulkarni/figuringout/assets/81710269/e605ba55-04eb-404d-a339-af66705ca0c4

* My `Wrangler.toml` file
Screenshot 2024-07-11 at 12 01 02 PM

* My `cloudflare r2 Bucket` screenshot where the profile pics are saved
Screenshot 2024-07-11 at 12 05 52 PM

**Comment by aadeshkulkarni** [comment]
@Ashutoshpadhi629  - Looks promising. 

A couple of things.
- Update the readme with the wrangler.toml changes, so that developers are aware about running `cp wrangler.sample.toml wrangler.toml` while setting up the project.
- For the bounty, please join the discord and DM your email / UPI Id, so that we can take next steps.

https://discord.gg/JtTQkzFY89

**Comment by Ashutoshpadhi629** [comment]
@aadeshkulkarni , updated the Readme file for `wrangler.sample.toml` file .

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni , updated the Readme file for `wrangler.sample.toml` file .

Please resolve merge conflicts

**Comment by Ashutoshpadhi629** [comment]
@aadeshkulkarni , Resolved the Merge Conflicts

**Comment by aadeshkulkarni** [comment]
Thank you for your contribution!

**Pull request merged**
